/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as FilesRouteImport } from './routes/files'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EmployeeFormRouteImport } from './routes/employee-form'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'

const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeFormRoute = EmployeeFormRouteImport.update({
  id: '/employee-form',
  path: '/employee-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/assistant': typeof AssistantRoute
  '/employee-form': typeof EmployeeFormRoute
  '/employees': typeof EmployeesRoute
  '/files': typeof FilesRoute
  '/import-export': typeof ImportExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/assistant': typeof AssistantRoute
  '/employee-form': typeof EmployeeFormRoute
  '/employees': typeof EmployeesRoute
  '/files': typeof FilesRoute
  '/import-export': typeof ImportExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/assistant': typeof AssistantRoute
  '/employee-form': typeof EmployeeFormRoute
  '/employees': typeof EmployeesRoute
  '/files': typeof FilesRoute
  '/import-export': typeof ImportExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/assistant'
    | '/employee-form'
    | '/employees'
    | '/files'
    | '/import-export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/assistant'
    | '/employee-form'
    | '/employees'
    | '/files'
    | '/import-export'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/assistant'
    | '/employee-form'
    | '/employees'
    | '/files'
    | '/import-export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AssistantRoute: typeof AssistantRoute
  EmployeeFormRoute: typeof EmployeeFormRoute
  EmployeesRoute: typeof EmployeesRoute
  FilesRoute: typeof FilesRoute
  ImportExportRoute: typeof ImportExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-form': {
      id: '/employee-form'
      path: '/employee-form'
      fullPath: '/employee-form'
      preLoaderRoute: typeof EmployeeFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AssistantRoute: AssistantRoute,
  EmployeeFormRoute: EmployeeFormRoute,
  EmployeesRoute: EmployeesRoute,
  FilesRoute: FilesRoute,
  ImportExportRoute: ImportExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
